mirthful_rcis/controllers/dashboard.py
from mirthful_rcis.lib import (
    libroom,
    librci,
    libuser
)

from mirthful_rcis.lib.authentication import login_required
from mirthful_rcis.lib.authorization import (
    user_can,
    Permission
)

from mirthful_rcis.lib.exceptions import (
    Unauthorized
)

from flask import (
    Blueprint,
    g,
    render_template,
    request
)

bp = Blueprint('dashboard', __name__) 

@bp.route('/', methods=['GET'])
@login_required
def main():
    """
    The "homepage". This is what a user sees when they first log-in.
    """
    logged_in_user = g.user

    # 1 - Fetch user settings for default buildings the user can view.
    #     1.1 If such a setting does not exist, default to all buildings
    # 2 - Try to fetch the rcis for the list of buildings we have.
    #     2.1 - If the call fails with `Unauthorized`, the user has no such access
    #           Fetch their own rcis only

    user_settings = libuser.get_user_settings(user_id=
                                              logged_in_user['user_id'])

    building_list = user_settings['default_buildings']

    if building_list is None:
        building_list = list(libroom.get_building_manifest().keys())

    try:
        rcis = librci.get_rcis_for_buildings(buildings=building_list,
                                             logged_in_user=logged_in_user)
    except Unauthorized:
        rcis = librci.get_rcis_for_user(user_id=logged_in_user['user_id'],
                                        logged_in_user=logged_in_user)

    
    user_permissions = libuser.get_user_permissions(user_id=logged_in_user['user_id'])

    display_search = user_can(permissions=Permission.MODERATE_RCIS,
                              user=logged_in_user)

    display_system_settings = user_can(permissions=Permission.MODERATE_SYSTEM,
                                       user=logged_in_user)

    

    return render_template('dashboard/main.html',
                           rcis=rcis,
                           display_search=display_search,
                           display_system_settings=display_system_settings)



@bp.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    """
    A view for searching through the rci database
    """

    if request.method == 'GET': 
        # Get request without a query
        return render_template('dashboard/search.html')

    search_string = request.form['search_string']

    results = librci.search_rcis(search_string=search_string,
                                 logged_in_user=g.user)

    return render_template('dashboard/search.html', 
                            search_string=search_string,
                            results=results)

mirthful_rcis/controllers/rci.py
from mirthful_rcis.lib import (
    common,
    librci,
    libroom,
    libuser
)
from mirthful_rcis.lib.authentication import login_required 

from flask import Blueprint
from flask import redirect, render_template, request, url_for
from flask import g

bp = Blueprint('rci', __name__, url_prefix='/rci')

@bp.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    """
    This view allows for creating a new rci
    """
    building_manifest = libroom.get_building_manifest() 
    users = libuser.get_users()

    if request.method == 'GET':

        return render_template('rci/new_rci_building_select.html',
                               building_manifest=building_manifest,
                               users=users)

    # Get the form contents
    user_id = request.form.get('user_id', None)
    building_name = request.form.get('building_name', None)
    room_name = request.form.get('room_name', None)


    # Can't create rci just yet, missing info...
    if user_id is None or building_name is None :
        return render_template('rci/new_rci_building_select.html',
                               building_manifest=building_manifest,
                               users=users)

    # Can't create rci just yet, missing info..
    elif room_name is None:
        user = common.get_user_record(user_id)
        new_rci = {
            'user_id': user_id,
            'firstname': user['firstname'],
            'lastname': user['lastname'],
            'building_name': building_name,
            'rooms': [ 
                x['room_name'] for x in building_manifest[building_name]
            ]
        }

        return render_template('rci/new_rci_room_select.html',
                               new_rci=new_rci)

    # We have all the information we need, create the rci...
    else:
        logged_in_user = g.get('user')

        rci = librci.create_rci(user_id=user_id,
                                building_name=building_name,
                                room_name=room_name,
                                logged_in_user=logged_in_user)

        return redirect(url_for('rci.edit', rci_id=rci['rci_id']))


@bp.route('/edit/<uuid:rci_id>', methods=['GET', 'POST'])
@login_required
def edit(rci_id):
    """
    The view for editing the contents of an rci document
    """
    rci_id = str(rci_id)

    if request.method == 'GET':
        rci = librci.get_rci_by_id(rci_id, full=True)
        return render_template('rci/edit.html', rci=rci)

mirthful_rcis/controllers/settings.py
from mirthful_rcis.lib.authentication import (
    login_required,
    admin_required
)

from flask import (
    Blueprint,
    render_template
)

bp = Blueprint('settings', __name__, url_prefix='/settings')

# TODO: Explain decorator order
@bp.route('/system', methods=['GET'])
@login_required
@admin_required
def system_settings():
    """
    Displays the main system settings page
    """

    return render_template('settings/system_settings.html')

mirthful_rcis/templates/dashboard/admin.html
{% extends 'base.html' %}

{% block title %}Rci Admin Dashboard - {{ g.user.username }} {% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}" />
{% endblock %}

{% block body %}

{% include "header.html" %}

<main>
    <section id="actions-section">
            <a class="reset-link component-picture-link" href="{{ url_for('rci.new') }}">
                <div></div>
                <span>NEW RCI</span>
            </a>
            <a class="reset-link component-picture-link" href="">
                <div></div>
                <span>PREFERENCES</span>
            </a>
    </section>
</main>


{% endblock %}

mirthful_rcis/templates/dashboard/main.html
{% from 'macros/rci_card.html' import rci_card %}

{% extends 'base.html' %}
{% block title %}Rci Dashboard - {{ g.user.username }} {% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}" />
{% endblock %}

{% block body %}

{% include "header.html" %}

<main>
    <section id="actions-section">
            <a class="reset-link component-picture-link" href="{{ url_for('rci.new') }}">
                <div></div>
                <span>NEW RCI</span>
            </a>
            {% if display_search %}
            <a class="reset-link component-picture-link" href="{{ url_for('dashboard.search') }}">
                <div></div>
                <span>SEARCH</span>
            </a>
            {% endif %}
            {% if display_system_settings %}
            <a class="reset-link component-picture-link" href="{{ url_for('settings.system_settings') }}">
                <div></div>
                <span>SYSTEM SETTINGS</span>
            </a>
            {% endif %}

    </section>
    <section>
        {% for rci in rcis %}
        {{ rci_card(rci) }}
        {% endfor %}
    </section>
</main>


{% endblock %}

mirthful_rcis/templates/dashboard/search.html
{% from 'macros/rci_card.html' import rci_card %}

{% extends 'base.html' %}

{% block title %}Rci Search {% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}" />
{% endblock %}

{% block body %}

{% include "header.html" %}

<main>
    <section id="actions-section">
        <form action="{{ url_for('dashboard.search') }}" method="post">
            <input name="search_string" 
                   placeholder="Search Rcis..." 
                   type="search" 
                   value="{{ search_string }}" />
        </form>
    </section>

    <section>
        {% for rci in results %}
        {{ rci_card(rci=rci) }}
        {% endfor %}
    </section>
</main>

{% endblock %}