mirthful_rcis/controllers/damage.py
from mirthful_rcis.lib import (
    common,
    librci,
    libroom,
    libuser,
    libdamage
)
from mirthful_rcis.lib.authentication import login_required 

from flask import Blueprint
from flask import redirect, render_template, request, url_for
from flask import g

bp = Blueprint('damage', __name__, url_prefix="/damage")

@bp.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    """
    This view allows for creating a new damage 
    """
    

    default_room_areas = [ 
        x['room_area_name']
        for x in libroom.get_default_room_areas()
    ]

    if request.method == 'GET':
        # If this is a get request, these will be query parameters
        user_id = request.args['user_id']
        rci_id = request.args['rci_id']

        return render_template('damage/new.html', 
                               room_areas=default_room_areas,
                               user_id=user_id,
                               rci_id=rci_id)

    rci_id = request.form['rci_id']
    item = request.form['item']
    text = request.form['text']
    logged_in_user = g.user

    libdamage.create_damage(logged_in_user=logged_in_user,
                            rci_id=rci_id,
                            item=item,
                            text=text,
                            image_url=None)

    return redirect(url_for('rci.edit', rci_id=rci_id))

@bp.route('/delete/<uuid:damage_id>', methods=['GET'])
@login_required
def delete(damage_id):
    """
    Deletes the damage with the given id
    """
    logged_in_user = g.user
    damage_id = str(damage_id)

    deleted_damage = libdamage.delete_damage(damage_id=damage_id, 
                                             logged_in_user=logged_in_user)

    rci_id = deleted_damage['rci_id']

    return redirect(url_for('rci.edit', rci_id=rci_id))

mirthful_rcis/controllers/rci.py
from mirthful_rcis.lib import (
    common,
    librci,
    libroom,
    libuser
)
from mirthful_rcis.lib.authentication import login_required 

from flask import Blueprint
from flask import redirect, render_template, request, url_for
from flask import g

bp = Blueprint('rci', __name__, url_prefix='/rci')

@bp.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    """
    This view allows for creating a new rci
    """
    building_manifest = libroom.get_building_manifest() 
    users = libuser.get_users()

    if request.method == 'GET':

        return render_template('rci/new_rci_building_select.html',
                               building_manifest=building_manifest,
                               users=users)

    # Get the form contents
    user_id = request.form.get('user_id', None)
    building_name = request.form.get('building_name', None)
    room_name = request.form.get('room_name', None)


    # Can't create rci just yet, missing info...
    if user_id is None or building_name is None :
        return render_template('rci/new_rci_building_select.html',
                               building_manifest=building_manifest,
                               users=users)

    # Can't create rci just yet, missing info..
    elif room_name is None:
        user = common.get_user_record(user_id)
        new_rci = {
            'user_id': user_id,
            'firstname': user['firstname'],
            'lastname': user['lastname'],
            'building_name': building_name,
            'rooms': [ 
                x['room_name'] for x in building_manifest[building_name]
            ]
        }

        return render_template('rci/new_rci_room_select.html',
                               new_rci=new_rci)

    # We have all the information we need, create the rci...
    else:
        logged_in_user = g.get('user')

        rci = librci.create_rci(user_id=user_id,
                                building_name=building_name,
                                room_name=room_name,
                                logged_in_user=logged_in_user)

        return redirect(url_for('rci.edit', rci_id=rci['rci_id']))


@bp.route('/edit/<uuid:rci_id>', methods=['GET', 'POST'])
@login_required
def edit(rci_id):
    """
    The view for editing the contents of an rci document
    """
    rci_id = str(rci_id)

    if request.method == 'GET':
        rci = librci.get_rci_by_id(rci_id, full=True)
        return render_template('rci/edit.html', rci=rci)

mirthful_rcis/templates/rci/edit.html
{% extends 'base.html' %}

{% block title %}Rci Form{% endblock %}

{% block css %}
{% endblock %}

{% block body %}
{% include "header.html" %}

<main>
    <section id="actions">
        <a class="reset-link component-button"
            href="{{ url_for('damage.new', rci_id=rci.rci_id, user_id=g.user['user_id']) }}">
            +New Damage
        </a>
    </section>
    <section>
        {%if rci.damages|length == 0 %}
        <p>No damages recorded.</p>
        {% else %}
        {% for item in rci.damages.keys() %}
        <div class="component-rci-damage-card">
            <span> {{ item }} </span>
            {% for damage in rci.damages[item] %}
            <div>
                <span> {{ damage.text }} </span>
                <span> -- by {{ damage.firstname }} {{ damage.lastname }}</span>
                <a href="{{ url_for('damage.delete', damage_id=damage.damage_id) }}">Remove</a>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        {% endif %}
    </section>
</main>
{% endblock %}

mirthful_rcis/templates/rci/new_rci_building_select.html
{% extends 'base.html' %}

{% block body %}

{% include "header.html" %}

<main>
    <form id="new-rci-form" action="{{ url_for('rci.new') }}" method="post">
        {# If the user is a student, they can only create an rci for themselves #}
        {% if g.user['role'] == 'student' %}
        <label>User:</label>
        <input type="text" hidden name="user_id" value="{{ g.get('user')['user_id'] }}"/>
        <input type="text" disabled value="{{ g['user']['firstname'] }} {{ g['user']['lastname'] }}" />

        {# staff and admin can create rcis for others #}
        {% else %}
        <label for"user">User:</label>
        <select class="component-select" id="user" name="user_id">
            {% for user in users %}
            <option value="{{ user.user_id }}">
            {{ user.firstname }} {{ user.lastname }} - {{ user.username }}
            </option>
            {% endfor %}
        </select>
        {% endif %}

        <label for="building">Select Building:</label>
        <select class="component-select" id="building" name="building_name">
            {% for building in building_manifest.keys() %}
            <option value="{{ building }}">{{ building }}</option>
            {% endfor %}
        </select>

        <button class="component-button" type="submit">Continue</button>
    </form>
</main>

{% endblock %}

mirthful_rcis/templates/rci/new_rci_room_select.html
{% extends 'base.html' %}

{% block body %}

{% include "header.html" %}

<main>
    <form id="new-rci-form" action="{{ url_for('rci.new') }}" method="post">
        <input type="text" disabled value="{{ new_rci.firstname }} {{ new_rci.lastname }}" />
        <input type="text" disabled value="{{ new_rci.building_name }}" />

        <label for="room">Select Room:</label>
        <select class="component-select" id="room" name="room_name">
            {% for room in new_rci.rooms %}
            <option value="{{ room }}">{{ room }}</option>
            {% endfor %}
        </select>

        <button class="component-button" type="submit">Create</button>

        <input type="text" hidden name="user_id" value="{{ new_rci.user_id }}" />
        <input type="text" hidden name="building_name" value="{{ new_rci.building_name }}" />
    </form>
</main>

{% endblock %}